### ISSUE TITLE
Import Error most likely due to a circular import

### ISSUE THREAD

**Issue by moorjuli** [GCoiffier/mouette#1]
Installing worked fine using pip, but when importing mouette in a script, i do get the following error. 
```
Exception has occurred: ImportError
cannot import name 'utils' from partially initialized module 'mouette' (most likely due to a circular import) (c:\Users\User\Documents\Mouette\.venv\lib\site-packages\mouette\__init__.py)
```
I do get the same error outside of a virtual enviroment both on windows and on ubuntu in a virtual machine

**Comment by GCoiffier** [comment]
Hi, 
Thanks for pointing this out ! It turns out I messed up the setup of subpackages. I uploaded a new version on Pypi and I am now able to run the library inside a virtual environment.

Guillaume

**Comment by moorjuli** [comment]
Hey,
thanks for the quick fix, now everything works as it should. Also thanks for your work with the project!
